version: '2.2'
services:
  es01:
    build: 
      context: .
      dockerfile: Dockerfile.aws-plugin
    image: localhost/elasticsearch:with-aws
    container_name: es01
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./data01:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml:ro
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - 9200:9200
    networks:
      - elastic
      - promnet
  es02:
    image: localhost/elasticsearch:with-aws
    container_name: es02
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9201:9200
    volumes:
      - ./data02:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml:ro
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    networks:
      - elastic
      - promnet
  es03:
    image: localhost/elasticsearch:with-aws
    container_name: es03
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./data03:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml:ro
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - 9202:9200
    networks:
      - elastic
      - promnet
  cerebro:
    image: lmenezes/cerebro
    # FIXME: add
    volumes:
      - ./cerebro/cerebro.conf:/opt/cerebro/conf/application.conf:ro
    ports:
      - 9000:9000
    networks:
      - elastic

  minio:
    image: minio/minio
    container_name: minio
    environment:
       - MINIO_ACCESS_KEY=AKIAAYAIDONOTUSE
       - MINIO_SECRET_KEY=iweib9taew3reuhi4ogo9idaiqu7aef3uuxe7zaph9
    entrypoint: sh
    command: -c 'mkdir -p /data/elasticsearch && /usr/bin/minio server /data'
    volumes:
      - ./snapshots:/data
    ports:
      - 9001:9000
    networks:
      - elastic

  exporter01:
    image: justwatch/elasticsearch_exporter
    command: ['--es.uri', 'http://es01:9200/']
    container_name: exporter01
    ports:
        - 9115:9114
    networks:
      - promnet
  exporter02:
    image: justwatch/elasticsearch_exporter
    command: ['--es.uri', 'http://es02:9200/']
    container_name: exporter02
    ports:
        - 9116:9114
    networks:
      - promnet
  exporter03:
    image: justwatch/elasticsearch_exporter
    command: ['--es.uri', 'http://es03:9200/']
    container_name: exporter03
    ports:
        - 9117:9114
    networks:
      - promnet
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./elasticsearch_rules.yml:/etc/prometheus/elasticsearch_rules.yml
    ports:
      - 9090:9090
    networks:
      - promnet
  alertmanager:
    image: prom/alertmanager
    ports:
        - 9093:9093
    networks:
      - promnet

networks:
  elastic:
    driver: bridge
  promnet:
    driver: bridge
