version: '2.2'
services:
  es01:
    image: elasticsearch:2.3
    container_name: es01
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./data01:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml:ro
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - 9200:9200
    networks:
      - elastic
  es02:
    image: elasticsearch:2.3
    container_name: es02
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9201:9200
    volumes:
      - ./data02:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml:ro
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    networks:
      - elastic
  es03:
    image: elasticsearch:2.3
    container_name: es03
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./data03:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml:ro
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - 9202:9200
    networks:
      - elastic

  minio:
    image: minio/minio
    container_name: minio
    environment:
       - MINIO_ACCESS_KEY=AKIAAYAIDONOTUSE
       - MINIO_SECRET_KEY=iweib9taew3reuhi4ogo9idaiqu7aef3uuxe7zaph9
    command: server /data
    volumes:
      - ./snapshots:/data
    ports:
      - 9000:9000
    networks:
      - elastic


networks:
  elastic:
    driver: bridge
