global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

# Rules
rule_files:
  - 'elasticsearch_rules.yml'

# Alertmanager
alerting:
  alertmanagers:
    - scheme: http
      static_configs:
      - targets:
        - "alertmanager:9093"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:9090']
  # ES 01
  - job_name: 'es01'
    scrape_interval: 5s
    static_configs:
      - targets: ['exporter01:9114']
  # ES 02
  - job_name: 'es02'
    scrape_interval: 5s
    static_configs:
      - targets: ['exporter02:9114']
  # ES 03
  - job_name: 'es03'
    scrape_interval: 5s
    static_configs:
      - targets: ['exporter03:9114']
